name: GitHub Actions Demo
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      # - name: Clone supercharge docs repository
      #   uses: actions/checkout@v2
      #   with:
      #     repository: buildpacks/samples
      #     path: samples/apps/java-maven

      - name: Build image
        uses: mamezou-tech/buildpacks-action@master
        with:
          image: "node-app"
          path: "node-buildpack"
          builder: "cnbs/sample-builder:alpine"

      - name: Run Trivy vulnerability scanner for buildpack
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "node-app"
          format: "template"
          template: "@/contrib/sarif.tpl"
          output: "trivy-results.sarif"
          
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'